on:
  push:

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: echo secret
        run: echo ${{ secrets.TEST_SECRET }}
      - name: echo secret through action
        uses: ./.github/actions/secret-action
